package com.example.finalthesis;

public class Questions {

   public String[] questions ={
            " Tablica 0 ",
            "1. Czym jest inkrementacja:",
            "2. Do czego odnoszą się modyfikatory public, private i protected:",
            "3. Tzw. notacja dużego O używana jest do:",
            "4. Co oznacza znak podwójnej równości == w językach pochodnych od języka C:",
            "5. Proces inicjalizacji zmiennej to:",
            "6. Czym jest tzw. IDE:",
            "7. Od jakiej liczby zaczyna się indeksacja tablic:",
            "8. Zakładając, że w danym języku programowania indeksacja tablicy rozpoczyna się od 5,\n" +
                    "ostatni indeks w tablicy dziesięcio elementowej będzie wynosił:",
            "9. Kompilator to:",
            "10. Strumienie w programowaniu używane są do:",
            "11. Przestrzenie nazw zapobiegają problemowi:", /*/ 39 */
            "12. Znakowy typ danych to:\n",
            "13. Prototyp funkcji:",
            "14. Zmiennoprzecinkowe typy danych różnią się najczęściej:",
            "15. Wzorce programowania (np. MVC) używamy do:",
            "16. Czym skutkuje próba ponownego przypisania wartości stałej w językach C-pochodnych:",
            "17. Konstruktor to:",
            "18. Za co odpowiada instrukcja „break”:",
            "19. W schematach blokowych, blok rombu oznacza:",
            "20. Polimorfizm umożliwia:",
            "21. Notacja ++ jest operatorem:",
            "22. Do czego służą wyjątki (exceptions):",
            "23. Algorytm Dijkstry w uproszczeniu służy do:",
            "24. Przy pomocy klauzuli ORDER BY języka SQL wykonamy:",
            "25. Wskaźniki w językach C-pochodnych to:",
            "26. Algorytmy zachłanne charakteryzują się:",
            "27. Tzw. kod Cezara, to algorytm:\n",
            "28. Funkcja rekurencyjna to:",
            "29. Typ zmiennej umożliwiającej przechowanie liczby zmiennoprzecinkowej to:",
            "30. Kolejka w rozumieniu jako abstrakcyjny typ danych to typ:",

    };

    public String[][] options = {

            {"Tablica 0","Tablica 0","Tablica 0","Tablica 0"},
            {"Zmniejszenie wartości o 1\n","Zwiększenie wartości o n, gdzie n>=2","Zwiększenie wartości o 1\n","Odpowiedz4"},
            {"Dziedziczenia","Przestrzeni nazw","Polimorfizmu","Polimorfizmu"},
            {"Opisu złożoności obliczeniowej algorytmu","Opisu ilości wątków używanych przez program","Opisu minimalnych wymagań systemowych do uruchomienia programu\n","Opisu minimalnych wymagań systemowych do uruchomienia programu\n"},
            {"Przypisania wartości zmiennej\n","Porównania wartości zmiennych\n","Żadne z powyższych\n","Żadne z powyższych\n"},
            {"Przypisanie wartości początkowej zmiennej","Utworzenie drugiej zmiennej, o takiej samej nazwie co pierwsza","Żadne z powyższych\n","Żadne z powyższych\n"},
            {"Algorytm","Środowisko programistyczne\n","Biblioteka przydatnych funkcji","Biblioteka przydatnych funkcji"},
            {"0\n","1","2","2"},
            {"16","15","14\n","Odpowiedz4"},
            {"Urządzenie używane do weryfikacji poprawności kodu programu","Program umożliwiający sprawne wyszukanie błędów w kodzie (przechodząc po nim linijka po linijce)\n","Program tłumaczący kod źródłowy programu na kod maszynowy","Odpowiedz4"},
            {"Wprowadzania lub wyprowadzania (wypisywania) wartości do i z programu","Szybkiej analizy działania programu","Określania złożoności pamięciowej programu","Odpowiedz4"},
            {"Niewystarczającej ilości pamięci wymaganej do prawidłowego działania programu","Konfliktu nazw (gdy dwa lub więcej elementów nosi taką samą nazwę)\n","Żadne z powyższych","Odpowiedz4"},
            {"char","string","int","Odpowiedz4"},
            {"Często nazywamy też definicją funkcji\n","Zawiera jedynie zwracany typ oraz parametry pobierane przez funkcję","To niepełna (ograniczona) wersja innej funkcji","Odpowiedz4"},
            {"Rozmiarem i dokładnością","Tylko precyzją","Tylko największą liczbą, jaką przy ich użyciu można zapisać\n","Odpowiedz4"},
            {"Określenia jednoznacznego sposobu nazywania funkcji i zmiennych","Ograniczenia prawdopodobieństwa nazwania zmiennych w ten sam sposób, gdy przy projekcie pracuje kilku\n" +
                    "programistów","Organizacji struktury programu","Odpowiedz4"},
            {"Błędem","Ostrzeżeniem","Niczym\n","Odpowiedz4"},
            {"Metoda wywoływana podczas tworzenia instancji klasy\n","Adres w pamięci, w którym znajduje się wartość zmiennej\n","Blok kodu, gdzie znajdują się deklaracje zmiennych","Odpowiedz4"},
            {"Za zakończenie programu","Za przerwanie wykonywania pętli\n","Za przerwanie wykonywania funkcji","Odpowiedz4"},
            {"Instrukcję wejścia/wyjścia","Instrukcję warunkową\n","Instrukcję początku/końca\n","Odpowiedz4"},
            {"Stworzenie wielu, niczym nieróżniących się funkcji (o takich samych nazwach, zwracanych typach i parametrach)","Używanie wielu zmiennych wskazujących w dokładnie to samo miejsce w pamięci","Żadne z powyższych","Odpowiedz4"},
            {"Jednostronnym","Dwustronnym","Nie jest operatorem","Odpowiedz4"},
            {"Do instrukcji warunkowych\n","Do obsługi błędów\n","Do opisu kodu\n","Odpowiedz4"},
            {"Obliczania pierwiastków dowolnej funkcji matematycznej","Określania najkrótszej odległości między dwoma punktami\n","Wyliczania n liczb pierwszych\n","Odpowiedz4"},
            {"Grupowanie\n","Sortowanie","Zawężenie wyników wyszukiwania\n","Odpowiedz4"},
            {"Funkcje wywołujące samą siebie","Zmienne przechowujące adres innej zmiennej\n","Złożony typ danych\n","Odpowiedz4"},
            {"Znajdowaniem zawsze najbardziej optymalnego rozwiązania problemu","Znajdowaniem zawsze najmniej optymalnego rozwiązania problemu","W zależności od danych, algorytm może znaleźć zarówno optymalne jak i nieoptymalne rozwiązanie problemu","Odpowiedz4"},
            {"Szyfrujący","Wyliczający pierwiastek dowolnego stopnia z liczby\n","Pobierający od użytkownika ciąg znaków i wypisujący go w odwrotnej kolejności","Odpowiedz4"},
            {"Taka, którą wykonuje się bez końca","Taka, która podczas swojego wykonania wykorzystuje wyniki z innych funkcji","Taka, która w trakcie wykonywania odwołuje się do samej siebie\n","Odpowiedz4"},
            {"double","int","string","Odpowiedz4"},
            {"FIFO (First-In-First-Out)","LIFO (Last-In-First-Out)","MIFO (Middle-In-First-Out)\n","Odpowiedz4"},

    };

    public char[] answer = {'A', // zerowy
                            'C',
                            'A',
                            'A',
                            'B',
                            'A',
                            'B',
                            'A',
                            'C',
                            'C',
                            'A',
                            'B',
                            'A',
                            'B',
                            'A',
                            'C',
                            'B',
                            'A',
                            'B',
                            'B',
                            'C',
                            'A',
                            'B',
                            'B',
                            'B',
                            'B',
                            'C',
                            'A',
                            'C',
                            'A',
                            'A',

    };

}
